config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'menu', to: 'static_pages#menu'
  get 'about', to: 'static_pages#about'
  get 'reminders', to: 'static_pages#reminders'
  get 'scores/categories/:id', to: 'scores#categories'
  get 'scores', to: 'scores#index'
  get 'scores/:id', to: 'scores#show'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'log_in' => 'sessions#create'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  post 'sign_up' => 'users#create'
  get 'categories', to: 'categories#index'
  get 'categories/:id', to: 'categories#show'
  get 'questions/:id', to: 'questions#show'
  get 'results/:id', to: 'users_answers#results'
  get 'users_answers/:id', to: 'users_answers#show'
  post 'users_answers', to: 'users_answers#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :questions
  has_many :scores

  def active(user_id)
    return true if self == Category.first || Score.exists?(user_id, id)

    prev_score = Score.find_by("category_id = #{prev.id} and user_id = #{user_id}")
    prev_score&.passed
  end

  def prev
    Category.where("id < #{id}").last
  end
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  has_many :users_answers
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :category
  has_many :choices
  has_many :user_answers

  def next
    category.questions.where('id > ?', id).first
  end

  def is_last?
    category.questions.last.id == id
  end

  def id_in_category
    category.questions.where('? >= id', id).count
  end
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  has_many :user_answers
  belongs_to :category
  belongs_to :user

  def self.current_score(user_id, category_id)
    is_exists = Score.where(user_id: user_id, category_id: category_id).exists?
    unless is_exists
      return Score.create(user_id: user_id, category_id: category_id)
    end

    Score.find_by(user_id: user_id, category_id: category_id)
  end

  def self.exists?(user_id, category_id)
    Score.where(user_id: user_id, category_id: category_id).exists?
  end

  def passed
    corrects_count >= 16
  end

  def corrects_count
    user_answers.select do |answer|
      answer.choice.correct
    end.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/models/user_answer.rb
# frozen_string_literal: true

class UserAnswer < ApplicationRecord
  belongs_to :score
  belongs_to :choice
  belongs_to :question

  def self.current_users_answer(score_id, question_id)
    UserAnswer.find_by(score_id: score_id, question_id: question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to log_in_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  layout "index", only: [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @question = @category.questions.first
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :logged_in_user

  def show
    @question = Question.find(params[:id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :logged_in_user


  def index
    @categories = Category.all
  end

  def show
    @questions_count = Category.find(params[:id]).questions.count
    @score = Score.current_score(session[:user_id], params[:id])
  end

  def categories
    score_list = Category.find(params[:id]).scores.map do |score|
      { 
        score: score.user_answers.select { |answer| answer.choice.correct }.count,
        user_mail: score.user.email
      } 
    end
    @scores = score_list.sort_by{ |s| -s[:score] }.take(10)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_user, only: [:destroy]

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to reminders_url, notice: "Logged in!"
    else
      flash.now[:login_alert] = "Email or password is invalid!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:menu, :about, :reminders]
  layout "index", only: [:about, :menu, :reminders]

  def home
  end

  def menu
  end

  def about
  end

  def reminders
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to the Sunnyee Quiz game!"
      session[:user_id] = @user.id
      redirect_to reminders_path
    else
      render "new"
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_answers_helper.rb
module UsersAnswersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/about.html.erb
<div class="container"> 
    <div class="row justify-content-center">
        <div class="display-4 p-2 title">About</div>
    </div>
    <div class="row justify-content-center">
        <div class="instruction"> 
            This app is made to test your knowledge
            and your ability in programming.<br/>
            this is not just a quiz, you learn from it also.
            Every Level has one programming languages that test your mind.
            Also test your skills.if you've done one level the next level will be unlock.
            the best thing you do is to choose the right answers of all the questions.
        </div>
    </div>
    <div class="row justify-content-center p-4">
        <%= link_to "Back to Menu", menu_path, class: "btn btn-success btn-lg" %>
    </div>
</div>

app/views/static_pages/home.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-7 display-4 subject'>Sunnyeee Game</div>
    <div class='col-5 text-right p-2'><%= link_to "Login", log_in_path, class: "btn btn-primary" %></div>
  </div>
  <div class='row justify-content-center p-5'>
    <div class='display-3 title'>Sunnyeee Quiz Game</div>
  </div>
  <div class='row justify-content-center'>
    <p>Sign up now! to play your game!</p>
  </div>
  <div class='row justify-content-center'>
    <%= link_to 'Sign up', sign_up_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/static_pages/menu.html.erb
<div class='container'>
    <div class="row justify-content-center p-3">
        <div class="title display-4"> Sunnyeee Quiz Game</div>
    </div>
    <div class='row justify-content-center p-3'>
        <div class="sub_title display-4"> Menu </div>
    </div>
    <div class="row justify-content-center p-2">
        <%= link_to 'Play', categories_path, class: 'btn btn-success btn-lg ' %>
    </div>
    <div class="row justify-content-center p-2">
        <%= link_to 'Score', scores_path, class: 'btn btn-primary btn-lg ' %>
    </div>
    <div class="row justify-content-center p-2">
        <%= link_to 'About', about_path, class: 'btn btn-info btn-lg ' %>
    </div>
    <div class="row justify-content-center p-2">
        <%= link_to 'Setting', "#", class: 'btn btn-danger btn-lg ' %>
    </div>
</div>

app/views/static_pages/reminders.html.erb
<div class="container">
    <div class='row justify-content-center'>
        <div class="title display-4 p-3">Reminders!</div>
    </div>
    <div class="row justify-content-center">
        <div class="content">
            Welcome to Sunnyeee Game!
            I would like to introduce you about how Sunnyeee Game is Great! 
            You can test what you've learned by taking following quizzes. 
            Each quiz consists of a question with multiple choices. 
            And there is one correct answers in these choices. 
            Select one choice you think is correct by clicking it. 
            Be honest! Because honesty is the best policy. 
            And also Enjoy while taking quizzes. Good luck!
        </div>
    </div>
    <div class="row justify-content-center p-4">
        <%= link_to 'Next', menu_path, class: "btn btn-success btn-lg" %>
    </div>
</div>