config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'menu', to: 'static_pages#menu'
  get 'about', to: 'static_pages#about'
  get 'reminders', to: 'static_pages#reminders'
  get 'scores/categories/:id', to: 'scores#categories'
  get 'scores', to: 'scores#index'
  get 'scores/:id', to: 'scores#show'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'log_in' => 'sessions#create'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  post 'sign_up' => 'users#create'
  get 'categories', to: 'categories#index'
  get 'categories/:id', to: 'categories#show'
  get 'questions/:id', to: 'questions#show'
  get 'results/:id', to: 'users_answers#results'
  get 'users_answers/:id', to: 'users_answers#show'
  post 'users_answers', to: 'users_answers#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :questions
  has_many :scores

  def active(user_id)
    return true if self == Category.first || Score.exists?(user_id, id)

    prev_score = Score.find_by("category_id = #{prev.id} and user_id = #{user_id}")
    prev_score&.passed
  end

  def prev
    Category.where("id < #{id}").last
  end
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  has_many :users_answers
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :category
  has_many :choices
  has_many :user_answers

  def next
    category.questions.where('id > ?', id).first
  end

  def is_last?
    category.questions.last.id == id
  end

  def id_in_category
    category.questions.where('? >= id', id).count
  end
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  has_many :user_answers
  belongs_to :category
  belongs_to :user

  def self.current_score(user_id, category_id)
    is_exists = Score.where(user_id: user_id, category_id: category_id).exists?
    unless is_exists
      return Score.create(user_id: user_id, category_id: category_id)
    end

    Score.find_by(user_id: user_id, category_id: category_id)
  end

  def self.exists?(user_id, category_id)
    Score.where(user_id: user_id, category_id: category_id).exists?
  end

  def passed
    corrects_count >= 16
  end

  def corrects_count
    user_answers.select do |answer|
      answer.choice.correct
    end.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/models/user_answer.rb
# frozen_string_literal: true

class UserAnswer < ApplicationRecord
  belongs_to :score
  belongs_to :choice
  belongs_to :question

  def self.current_users_answer(score_id, question_id)
    UserAnswer.find_by(score_id: score_id, question_id: question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to log_in_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  layout "index", only: [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @question = @category.questions.first
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :logged_in_user

  def show
    @question = Question.find(params[:id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :logged_in_user


  def index
    @categories = Category.all
  end

  def show
    @questions_count = Category.find(params[:id]).questions.count
    @score = Score.current_score(session[:user_id], params[:id])
  end

  def categories
    score_list = Category.find(params[:id]).scores.map do |score|
      { 
        score: score.user_answers.select { |answer| answer.choice.correct }.count,
        user_mail: score.user.email
      } 
    end
    @scores = score_list.sort_by{ |s| -s[:score] }.take(10)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_user, only: [:destroy]

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to reminders_url, notice: "Logged in!"
    else
      flash.now[:login_alert] = "Email or password is invalid!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:menu, :about, :reminders]
  layout "index", only: [:about, :menu, :reminders]

  def home
  end

  def menu
  end

  def about
  end

  def reminders
  end
end

app/controllers/users_answers_controller.rb
# frozen_string_literal: true

class UsersAnswersController < ApplicationController
  before_action :logged_in_user

  def create
    question = Question.find(params[:question_id])
    @score = Score.current_score(session[:user_id], question.category_id)
    @answer = UserAnswer.find_or_initialize_by(score_id: @score.id, question_id: params[:question_id])
    @answer.choice_id = params[:choice_id]
    if @answer.save
      redirect_to action: :show, id: @answer.id
    else
      flash[:question_alert] = 'Error while sending answers!'
      redirect_to controller: 'questions', action: 'show', id: question.id
    end
  end

  def show
    @answer = UserAnswer.find(params[:id])
  end

  def results
    @category = Category.find(params[:id])
    @score = Score.find_by(user_id: current_user, category_id: @category.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to the Sunnyee Quiz game!"
      session[:user_id] = @user.id
      redirect_to reminders_path
    else
      render "new"
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_answers_helper.rb
module UsersAnswersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="container">   
    <div class="row justify-content-center p-3">
        <div class="title display-4">Categories</div>
    </div>
    <div class="row justify-content-center p-4">
        <% @categories.each do |category| %>
            <div class="category">
                <%= link_to category.title, "/categories/#{category.id}", class: "btn btn-primary btn-lg #{!category.active(@current_user.id) ? "disabled" : ""}" %>
            </div>
        <% end %>
    </div>
    <div class="row justify-content-center p-5">
        <%= link_to "Menu", menu_path, class: "btn btn-warning btn-lg" %>
    </div>
</div>

app/views/categories/show.html.erb
<div class="description">    
    <div class="direction">
        <h1>Direction:</h1>
        <%= @category.description %>
        <div>
            This quiz consists of 20 questions.
            To be successful, you need to choose the best answer and get scores higher than 15. 
            If you could be successful, the next category will be unlocked. 
            If you get scores less than 16, you need to try the category quiz from the first question.
        </div>
        <div><%= link_to "Next", "/questions/#{@question.id}", class: "btn btn-info btn-lg" %></div>
    </div>
</div>

app/views/questions/show.html.erb
<div class="container">    
    <div class="row justify-content-center p-4">
        <%= form_with url: '/users_answers' do %>
            <% if flash[:question_alert] %>
            <!-- Only display login_alert flash message here -->
                <%= content_tag :div, flash[:question_alert], :id => "question_alert" %>
            <% end %>
            <div class="content">
                <%= @question.id_in_category %>. <%= @question.content %>
            </div>
            <div>
                <%= hidden_field_tag 'question_id', @question.id  %>
            </div>
            <div class="choices">
                <% @question.choices.each do |choice| %>
                    <div>
                        <label>
                            <%= radio_button_tag('choice_id', choice.id) %> <%= choice.content %>
                        </label>
                    </div>
                <% end %>
            </div>
            <div class="submit">
                <%= submit_tag("Next", class: 'btn btn-success btn-lg')%>
            </div>
        <% end %>
    </div>
</div>

app/views/scores/categories.html.erb
<div class="record"> 
    <div class="list">
        <h1>List Of Scores</h1>
        <% @scores.each do |s| %>
            <div class="outcome">
                <div class="username"><%= s[:user_mail] %></div>
                <div class="achievement"><%= s[:score] %></div>
            </div>
        <% end %>
        <span><%= link_to 'Back', scores_path, class: "btn btn-info btn-lg" %></span>
        <span><%= link_to 'Menu', menu_path, class: "btn btn-success btn-lg" %></span>
    </div>
</div>

app/views/scores/index.html.erb
<div class="category">    
    <div class="score">
        <h1> Highest Score </h1>
        <% @categories.each do |category| %>
            <h2><%= link_to category.title, "/scores/categories/#{category.id}", class: "btn btn-default btn-lg" %></h2>
        <% end %>
        <%= link_to 'Menu', menu_path, class: "btn btn-primary btn-lg" %>
     </div>
</div>

app/views/scores/show.html.erb
<div class="result_of_users_answers">    
    <div class="content">
        <div class="total_score"><%= @score.corrects_count %> / <%= @questions_count %></div>
        <% if @score.passed %>
            <div class="result_title succeed"> Congratulations!<br>Good Job!</div>
            <%= image_tag 'verygood.gif' %><br> 
            <div>
                Congratulations! You're now able to play the 
                next Category.
            </div>
            <div><%= link_to "Category Menu", categories_path, class: "button proceed", :onclick => "audio.pause()" %></div>
        <% else %>
            <div class="result_title failed">Ooooooppss..<br>FAILED!</div>
            <%= image_tag 'crying.gif'%>
            <div>
                Sorry you're not able to play the next Category.
                You must get atlist higher than 15 scores.
            </div>
            <div><%= link_to "Back to menu", menu_path, class: "button back", :onclick => "audio.pause()" %></div>
        <% end %>
        <div><%= link_to "Results", "/results/#{@score.category_id}", class: "btn btn-success btn-lg" %></div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy',  user,  method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">  
  <div class="row justify-content-center">
    <div class="title display-4 p-5">Sign Up</div>
  </div>
  <div class="row justify-content-center">
    <%= form_for @user, url: sign_up_path do |f| %>
      <% if @user.errors.any? %>
        <div class="invalid_input">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div> 
      <% end %>
      <div class="input">
        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
      </div>
      <div class="input">
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
      <div class="input">
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password_Confirmation" %>
      </div>
      <div>
        <%= f.submit "Create my account", class: "btn btn-success btn-lg" %>
      </div>
    <% end %>
  </div>
  <div class="row justify-content-center">
    <div class="login"> Already have an account?just click
      <%= link_to "Login", log_in_path, class: "btn btn-primary btn-lg"%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>