config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'menu', to: 'static_pages#menu'
  get 'about', to: 'static_pages#about'
  get 'reminders', to: 'static_pages#reminders'
  get 'scores/categories/:id', to: 'scores#categories'
  get 'scores', to: 'scores#index'
  get 'scores/:id', to: 'scores#show'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  post 'log_in' => 'sessions#create'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  post 'sign_up' => 'users#create'
  get 'categories', to: 'categories#index'
  get 'categories/:id', to: 'categories#show'
  get 'questions/:id', to: 'questions#show'
  get 'results/:id', to: 'users_answers#results'
  get 'users_answers/:id', to: 'users_answers#show'
  post 'users_answers', to: 'users_answers#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :questions
  has_many :scores

  def active(user_id)
    return true if self == Category.first || Score.exists?(user_id, id)

    prev_score = Score.find_by("category_id = #{prev.id} and user_id = #{user_id}")
    prev_score&.passed
  end

  def prev
    Category.where("id < #{id}").last
  end
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  has_many :users_answers
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :category
  has_many :choices
  has_many :user_answers

  def next
    category.questions.where('id > ?', id).first
  end

  def is_last?
    category.questions.last.id == id
  end

  def id_in_category
    category.questions.where('? >= id', id).count
  end
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  has_many :user_answers
  belongs_to :category
  belongs_to :user

  def self.current_score(user_id, category_id)
    is_exists = Score.where(user_id: user_id, category_id: category_id).exists?
    unless is_exists
      return Score.create(user_id: user_id, category_id: category_id)
    end

    Score.find_by(user_id: user_id, category_id: category_id)
  end

  def self.exists?(user_id, category_id)
    Score.where(user_id: user_id, category_id: category_id).exists?
  end

  def passed
    corrects_count >= 16
  end

  def corrects_count
    user_answers.select do |answer|
      answer.choice.correct
    end.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/models/user_answer.rb
# frozen_string_literal: true

class UserAnswer < ApplicationRecord
  belongs_to :score
  belongs_to :choice
  belongs_to :question

  def self.current_users_answer(score_id, question_id)
    UserAnswer.find_by(score_id: score_id, question_id: question_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  layout "index", only: [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @question = @category.questions.first
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :logged_in_user

  def show
    @question = Question.find(params[:id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :logged_in_user


  def index
    @categories = Category.all
  end

  def show
    @questions_count = Category.find(params[:id]).questions.count
    @score = Score.current_score(session[:user_id], params[:id])
  end

  def categories
    score_list = Category.find(params[:id]).scores.map do |score|
      { 
        score: score.user_answers.select { |answer| answer.choice.correct }.count,
        user_mail: score.user.email
      } 
    end
    @scores = score_list.sort_by{ |s| -s[:score] }.take(10)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_user, only: [:destroy]

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to reminders_url, notice: "Logged in!"
    else
      flash.now[:login_alert] = "Email or password is invalid!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to the Sunnyee Quiz game!"
      session[:user_id] = @user.id
      redirect_to reminders_path
    else
      render "new"
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_answers_helper.rb
module UsersAnswersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="header row p-2">
    <div class="col-7 username">
        <%= @current_user.email %>
    </div>
    <div class="col-5 text-right">
        <%= link_to "LogOut", log_out_path%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html>
  <head>
    <title>Sunnyeee Quiz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag  "application" %>
    <%= javascript_include_tag  "application" %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" data-turbolinks-eval="true">
      var audio = new Audio();
      document.addEventListener('turbolinks:load', function() {
        var is_target_page = document.querySelector('.questions,.users_answers,.scores.show,.results');
        if (audio.paused && is_target_page) {
          play(audio);
        }
      });
      async function play(audio) {
        audio.src = "/assets/Funny-background-music-for-videos-and-games.mp3";
        audio.loop = true;
        audio.autoplay = true;
        audio.play();
      }
    </script>
  </head>
  <body>
    <div class="top_wrapper <%= controller_name %> <%= action_name %> ">
      <% if flash[:notice] || flash[:alert] %>
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html> 
<html>
  <head>
    <title>Sunnyeee Quiz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag  "application" %>
    <%= javascript_include_tag  "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="top_content <%= controller_name %> <%= action_name %>">
      <%= render 'layouts/header' %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
      </div>
    </div>
  </body>
</html>